#!/bin/bash
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Input file listing acc files: '$input_file'"
    local_input_name=$(dx describe "$input_file" --name)
    dx download "$input_file" -o "$local_input_name"

mkdir -p downloaded_files

while IFS= read -r line; do
    # Recover the original filename of the input file
    local_input_file=$(dx describe "$line" --name)
    echo Original input file name: "$local_input_file"
    dx download "$line" -o downloaded_files/
done <"$local_input_name"

ls downloaded_files | xargs -P 10 -I {} stepcount downloaded_files/{}
    
    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    # Recover the original filename of the input file

    # Download the input file to the local file system

    # Fill in your application code here.

    # Run the stepcount program

    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    output_files=($(dx upload -r outputs --brief))

    for i in "${!output_files[@]}"; do
        dx-jobutil-add-output output_dir "${output_files[$i]}" --class=array:file
    done

}
